swagger: "2.0"
schemes:
- http
#- https
produces:
- application/com.finalapproachsofware.wildcat.v1+json
consumes:
- application/com.finalapproachsofware.wildcat.v1+json
info:
  description: An api for managing common needs of SAAS applications
  title: Bedrock service
  version: 1.0.0
paths:
  /tenants:
    #TENANT SEARCH
    get:
      tags:
        - tenants
      operationId: search
      responses:
        200:
          description: List of tenants
          schema:
            type: array
            items:
              $ref: "#/definitions/tenant"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    #TENANT CREATE
    post:
      tags:
        - tenants
      operationId: create
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/tenant"
      responses:
        201:
          description: Ok
          schema:
            $ref: "#/definitions/tenant"
        default:
          description: Error
          schema:
            $ref: "#/definitions/error"
  #/tenants/{id}:
  #/users:
  #/users/{id}:
  #/edditions:
  #/edditions/{id}: 
  #/roles:
  #/roles/{id}:
definitions:
  tenant:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        readOnly: true
      name:
        type: string
        minLength: 1
      active:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string