package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/com.finalapproachsofware.wildcat.v1+json"
  ],
  "produces": [
    "application/com.finalapproachsofware.wildcat.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "An api for managing common needs of SAAS applications",
    "title": "Bedrock service",
    "version": "1.0.0"
  },
  "paths": {
    "/tenants": {
      "get": {
        "tags": [
          "tenants"
        ],
        "operationId": "search",
        "responses": {
          "200": {
            "description": "List of tenants",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/tenant"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "tenants"
        ],
        "operationId": "create",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/tenant"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/tenant"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "tenant": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "active": {
          "type": "boolean"
        },
        "id": {
          "type": "string",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
}`))
}
